Repository SmartBrush/Frontend, pull requests merged in 2025-08, with the labels that each got.

#37 ✨ [FEAT] 두피 진단 페이지 API 연결
  index.html
  src/assets/logo.png
  src/components/Auth/BlueBox.tsx
  src/components/Main/CameraUploadButton.tsx
  src/components/Result/ScalpRadarChart.tsx
  src/layout/RootLayout.tsx
  src/pages/ResultPage.tsx
  src/pages/SignInPage.tsx
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#38 [Feat] 게시글 api연결 및 UI수정
  package.json
  src/App.tsx
  src/assets/edit.png
  src/assets/hot1.png
  src/assets/hot2.png
  src/assets/hot3.png
  src/assets/profile.png
  src/components/Community/ConcernCard.tsx
  src/components/Community/HotTopicCard.tsx
  src/components/Community/HotTopicsSection.tsx
  src/components/Community/SearchBar.tsx
  src/components/Community/SharedConcernsSection.tsx
  src/components/Community/TabMenu.tsx
  src/pages/CommunityPage.tsx
  src/pages/ConcernDetailPage.tsx
  src/pages/ConcernListPage.tsx
  src/pages/ConcernPostPage.tsx
  src/pages/HotTopicListPage.tsx
  yarn.lock
Labels: ✨ Feature, 🎨 Html&css

#39 [FEAT] 메인 페이지 API 연결
  src/apis/diagnosis.ts
  src/assets/badIcon.png
  src/assets/badIcon.svg
  src/assets/goodIcon.png
  src/assets/goodIcon.svg
  src/assets/normalIcon.png
  src/assets/normalIcon.svg
  src/components/Main/Calendar.tsx
  src/components/Main/CalendarGrid.tsx
  src/components/Main/CalendarHeader.tsx
  src/components/Main/TodayScalpStatus.tsx
  src/layout/RootLayout.tsx
  src/pages/MainPage.tsx
  src/pages/ResultPage.tsx
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#44 [Feat] 마이페이지 일부
  src/App.tsx
  src/apis/api.ts
  src/assets/green_win.png
  src/assets/profile.png
  src/assets/red_win.png
  src/assets/yellow_win.png
  src/components/Community/TabMenu.tsx
  src/components/Mypage/MyPageMenuItem.tsx
  src/components/Mypage/UserProfile.tsx
  src/pages/EditProfilePage.tsx
  src/pages/MainPage.tsx
  src/pages/Mypage.tsx
Labels: ✨ Feature, 🎨 Html&css

#70 ✨ [FEAT] 질문 유무 확인
  src/components/ScalpSurvey/Question1_1.tsx
  src/components/ScalpSurvey/Question2_1.tsx
  src/components/ScalpSurvey/Question2_2.tsx
  src/components/ScalpSurvey/Question3_1.tsx
  src/components/ScalpSurvey/Question3_2.tsx
  src/components/ScalpSurvey/Question4_1.tsx
  src/components/ScalpSurvey/Question4_2.tsx
  src/pages/ResultPage.tsx
  src/pages/ScalpSurveyPage.tsx
  src/pages/SignInPage.tsx
Labels: ✨ Feature

#73 🐛 [FIX] 메인 페이지 수정
  src/apis/diagnosis.ts
  src/components/Main/LoadingOverlay.tsx
  src/components/Main/Spinner.tsx
  src/components/Main/TodayScalpStatus.tsx
  src/components/NavBar/NavBar.tsx
  src/layout/RootLayout.tsx
  src/pages/MainPage.tsx
  src/pages/SignInPage.tsx
Labels: 🐛 BugFix, ✨ Feature, 🎨 Html&css

#75 🐛 [FIX] 이미지 수정
  src/pages/ResultPage.tsx
Labels: 🐛 BugFix
